### ISSUE TITLE
Flesh out example project some more

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/netable#94]
From: https://github.com/steamclock/netable/pull/93

Things we should add:
- [] The params just being a raw dictionary rather than a struct
- [] Adding a custom finalize implementation
- [] Adding a custom decode implementation

Larger things to consider adding:
>  I know it's not really core to showing off Netable itself, but it would be nice if the "create post" API actually did something to the state of the posts when you get them. Seems like it'd be fairly straightforward to just decode the post in the "server" and keep like an in memory list of create posts and then when it's doing the "get post" send back both the json data AND the in memory posts.

> Seems like with iOS 13 as the min platform we should be able to use SwiftUI if we want. AIUI It's only if we're supporting 12 that we need UIKit example code to make it possible to runt he test app on 12, but I'm pretty sure we already dropped 12 support

**Comment by amyoulton** [comment]
@brendanlensink I'm guessing we can close this now 😅
